name: Build DevTools frontend

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: src
    - name: Restore gclient workspace cache
      uses: actions/cache/restore@v3
      with:
        path: |
          .
          !src
          !!src/out
          !!src/.cipd
        key: ${{ runner.os }}-${{ hashFiles('src/.github/workflows/*') }}-gclient-workspace-${{ hashFiles('src/DEPS') }}
        restore-keys: |
          ${{ runner.os }}-${{ hashFiles('src/.github/workflows/*') }}-gclient-workspace-
    - name: setup-depot-tools
      uses: newkdev/setup-depot-tools@v1.0.1
    - name: Sync gclient workspace
      run: |
        gclient config --unmanaged src --name src
        gclient sync --no-history
    - name: Build DevTools frontend
      run: |
        cd src
        gn gen out/Default
        autoninja -C out/Default
    - uses: ./src/.github/actions/upload-artifact
      with:
        name: dist-front_end
        path: src/out/Default/gen/front_end
    - name: Save gclient workspace cache
      uses: actions/cache/save@v3
      with:
        path: |
          .
          !src
          !!src/out
          !!src/.cipd
        key: ${{ runner.os }}-${{ hashFiles('.github/workflows/*') }}-gclient-workspace-${{ hashFiles('src/DEPS') }}
  